.\objects\iica.o: SourceCode\CMS_SDK_1D0D5\Driver\src\iica.c
.\objects\iica.o: D:\M14D\PersonalProject\MCU_SystemSoftware\Rtos_Project_Folder\BAT32_FreeRtos_Project\RTE\Device\BAT32A237KH40NB\userdefine.h
.\objects\iica.o: .\SourceCode\CMS_SDK_1D0D5\Device\Include\BAT32A237.h
.\objects\iica.o: .\SourceCode\CMS_SDK_1D0D5\CMSIS\Include\core_cm0plus.h
.\objects\iica.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\iica.o: .\SourceCode\CMS_SDK_1D0D5\CMSIS\Include\core_cmInstr.h
.\objects\iica.o: .\SourceCode\CMS_SDK_1D0D5\CMSIS\Include\core_cmFunc.h
.\objects\iica.o: .\SourceCode\CMS_SDK_1D0D5\Device\Include\system_BAT32A237.h
.\objects\iica.o: .\SourceCode\CMS_SDK_1D0D5\Driver\inc\iica.h
.\objects\iica.o: .\SourceCode\UsrCode\Usr_I2CA_Slave.h
