.\objects\usr_gpio.o: SourceCode\UsrCode\Usr_GPIO.c
.\objects\usr_gpio.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\objects\usr_gpio.o: .\SourceCode\CMS_SDK_1D0D5\Device\Include\BAT32A237.h
.\objects\usr_gpio.o: .\SourceCode\CMS_SDK_1D0D5\CMSIS\Include\core_cm0plus.h
.\objects\usr_gpio.o: .\SourceCode\CMS_SDK_1D0D5\CMSIS\Include\core_cmInstr.h
.\objects\usr_gpio.o: .\SourceCode\CMS_SDK_1D0D5\CMSIS\Include\core_cmFunc.h
.\objects\usr_gpio.o: .\SourceCode\CMS_SDK_1D0D5\Device\Include\system_BAT32A237.h
.\objects\usr_gpio.o: D:\M14D\PersonalProject\MCU_SystemSoftware\Rtos_Project_Folder\BAT32_FreeRtos_Project\RTE\Device\BAT32A237KH40NB\userdefine.h
.\objects\usr_gpio.o: .\SourceCode\CMS_SDK_1D0D5\Driver\inc\adc.h
.\objects\usr_gpio.o: .\SourceCode\CMS_SDK_1D0D5\Driver\inc\gpio.h
.\objects\usr_gpio.o: SourceCode\UsrCode\Usr_GPIO.h
.\objects\usr_gpio.o: SourceCode\UsrCode\Usr_I2C.h
.\objects\usr_gpio.o: SourceCode\UsrCode\Usr_Uart.h
.\objects\usr_gpio.o: SourceCode\UsrCode\Usr_Config.h
.\objects\usr_gpio.o: SourceCode\UsrCode\Usr_Debug.h
.\objects\usr_gpio.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdio.h
.\objects\usr_gpio.o: SourceCode\UsrCode\Usr_Task.h
.\objects\usr_gpio.o: SourceCode\UsrCode\Usr_ADC.h
