/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.40.0.0
 *
 * Project: 'BAT32_FreeRTOS_Proj' 
 * Target:  'BAT32_FreeRTOS' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "BAT32A237.h"



#endif /* RTE_COMPONENTS_H */
