#ifndef __USR_DATAFLASH_H__
#define __USR_DATAFLASH_H__

#include "Usr_Config.h"



#define DEF_DATAFLASH_EN            1

#if 0
#define DEF_DF_PARAM_STARTADDR      (0x00500000)
#define DEF_DF_PARAM_OVERADDR       (0x00500100)
#define DEF_DF_DATA_LEN             (DEF_DF_PARAM_OVERADDR-DEF_DF_PARAM_STARTADDR)
#endif

#if 0
#define DEF_DF_PARAM_STARTADDR      (0x00500100)
#define DEF_DF_PARAM_OVERADDR       (0x00500200)
#define DEF_DF_DATA_LEN             (DEF_DF_PARAM_OVERADDR-DEF_DF_PARAM_STARTADDR)
#endif

#if 1
#define DEF_DF_PARAM_STARTADDR      (0x00500200)
#define DEF_DF_PARAM_OVERADDR       (0x00500300)
#define DEF_DF_DATA_LEN             (DEF_DF_PARAM_OVERADDR-DEF_DF_PARAM_STARTADDR)
#endif


#define DEF_TIME_SN_INDEX           (4)       // 0x04
#define DEF_TIME_SN_ADDRSTART       (DEF_DF_PARAM_STARTADDR+DEF_TIME_SN_INDEX)

#define DEF_TRAWBASE_INDEX          (10)     // 0x0A
#define DEF_TRAWBASE_ADDRSTART      (DEF_DF_PARAM_STARTADDR+DEF_TIME_SN_INDEX)

#define DEF_TCOMP_P0_INDEX          (12)      // 0x0C
#define DEF_TCOMP_P0_ADDRSTART      (DEF_DF_PARAM_STARTADDR+DEF_TIME_SN_INDEX)

#define DEF_TCOMP_P1_INDEX          (16)      // 0x10
#define DEF_TCOMP_P1_ADDRSTART      (DEF_DF_PARAM_STARTADDR+DEF_TIME_SN_INDEX)

#define DEF_TCOMP_P2_INDEX          (20)      // 0x14
#define DEF_TCOMP_P2_ADDRSTART      (DEF_DF_PARAM_STARTADDR+DEF_TIME_SN_INDEX)

#define DEF_TCOMP_P3_INDEX          (24)      // 0x18
#define DEF_TCOMP_P3_ADDRSTART      (DEF_DF_PARAM_STARTADDR+DEF_TIME_SN_INDEX)



#define DEF_PREHEATTIME_INDEX       (32)
#define DEF_PREHEATTIME_ADDRSTART   (DEF_DF_PARAM_STARTADDR+DEF_PREHEATTIME_INDEX)

#define DEF_COOLTIME_INDEX          (34)
#define DEF_COOLTIME_ADDRSTART      (DEF_DF_PARAM_STARTADDR+DEF_COOLTIME_INDEX)

#define DEF_FILTERCNT_INDEX         (36)
#define DEF_FILTERCNT_ADDRSTART     (DEF_DF_PARAM_STARTADDR+DEF_FILTERCNT_INDEX)

#define DEF_GASTYPE_INDEX           (38)
#define DEF_GASTYPE_ADDRSTART       (DEF_DF_PARAM_STARTADDR+DEF_GASTYPE_INDEX)

#define DEF_TABLEX_INDEX            (40)
#define DEF_TABLEX_ADDRSTART        (DEF_DF_PARAM_STARTADDR+DEF_TABLEX_INDEX)

#define DEF_TABLEY_INDEX            (72)
#define DEF_TABLEY_ADDRSTART        (DEF_DF_PARAM_STARTADDR+DEF_TABLEY_INDEX)

#define DEF_DC_Y_INDEX              (104)
#define DEF_DC_Y_ADDRSTART          (DEF_DF_PARAM_STARTADDR+DEF_DC_Y_INDEX)

#define DEF_DELTA_RAW_INDEX         (106)
#define DEF_DELTA_RAW_ADDRSTART     (DEF_DF_PARAM_STARTADDR+DEF_DELTA_RAW_INDEX)

#define DEF_DELTA_PPM_INDEX         (108)
#define DEF_DELTA_PPM_ADDRSTART     (DEF_DF_PARAM_STARTADDR+DEF_DELTA_PPM_INDEX)


#define DEF_HUMCOMP_PARAM_INDEX     (112)
#define DEF_HUMCOMP_PARAM_ADDRSTART (DEF_DF_PARAM_STARTADDR+DEF_HUMCOMP_PARAM_INDEX)

#define DEF_HUMCOMP_FLAG_INDEX      (144)
#define DEF_HUMCOMP_FLAG_ADDRSTART  (DEF_DF_PARAM_STARTADDR+DEF_HUMCOMP_FLAG_INDEX)

#define DEF_PRESCOMP_PARAM_INDEX    (152)
#define DEF_PRESCOMP_PARAM_ADDRSTART (DEF_DF_PARAM_STARTADDR+DEF_PRESCOMP_PARAM_INDEX)

#define DEF_PRESCOMP_PBASE_INDEX     (164)
#define DEF_PRESCOMP_PBASE_ADDRSTART (DEF_DF_PARAM_STARTADDR+DEF_PRESCOMP_PBASE_INDEX)

#define DEF_PRESCOMP_FLAG_INDEX     (166)
#define DEF_PRESCOMP_FLAG_ADDRSTART (DEF_DF_PARAM_STARTADDR+DEF_PRESCOMP_FLAG_INDEX)

#define DEF_TMPRATE_P_INDEX         (168)
#define DEF_TMPRATE_P_ADDRSTART     (DEF_DF_PARAM_STARTADDR+DEF_TMPRATE_P_INDEX)


#define DEF_HTCOMP_TRAWBASE_INDEX   (176)
#define DEF_HTCOMP_TRAWBASE_ADDRSTART   (DEF_DF_PARAM_STARTADDR+DEF_HTCOMP_TRAWBASE_INDEX)

#define DEF_HTCOMP_HTRAWBASE_INDEX  (178)
#define DEF_HTCOMP_HTRAWBASE_ADDRSTART  (DEF_DF_PARAM_STARTADDR+DEF_HTCOMP_HTRAWBASE_INDEX)

#define DEF_HTCOMP_KH_INDEX         (180)
#define DEF_HTCOMP_KH_ADDRSTART     (DEF_DF_PARAM_STARTADDR+DEF_HTCOMP_KH_INDEX)

#define DEF_HTCOMP_SP_INDEX         (182)
#define DEF_HTCOMP_SP_ADDRSTART     (DEF_DF_PARAM_STARTADDR+DEF_HTCOMP_SP_INDEX)

#define DEF_HTCOMP_KS_INDEX         (184)
#define DEF_HTCOMP_KS_ADDRSTART     (DEF_DF_PARAM_STARTADDR+DEF_HTCOMP_KS_INDEX)

#define DEF_HTCOMP_DP0_INDEX        (186)
#define DEF_HTCOMP_DPO_ADDRSTART    (DEF_DF_PARAM_STARTADDR+DEF_HTCOMP_DP0_INDEX)


#define DEF_HUMI_RATE_INDEX         (188)
#define DEF_HUMI_RATE_ADDRSTART     (DEF_DF_PARAM_STARTADDR+DEF_HUMI_RATE_INDEX)

#define DEF_CONCEN_THRE_INDEX       (192)
#define DEF_CONCEN_THRE_ADDRSTART   (DEF_DF_PARAM_STARTADDR+DEF_CONCEN_THRE_INDEX)

#if((defined(DEBUG_SELF_MONITORING_EN))&&(DEBUG_SELF_MONITORING_EN == 1))
#define DEF_SELFMONI_STATE_INDEX            (200)
#define DEF_SELFMONI_SATTE_ADDRSTART        (DEF_DF_PARAM_STARTADDR+DEF_SELFMONI_STATE_INDEX)

#define DEF_SELFMONI_DRIFTLIMIT_INDEX       (202)
#define DEF_SELFMONI_DRIFTLIMIT_ADDRSTART   (DEF_DF_PARAM_STARTADDR+DEF_SELFMONI_DRIFTLIMIT_INDEX)

#define DEF_SELFMONI_DRIFTFAULT_INDEX       (204)
#define DEF_SELFMONI_DRIFTFAULT_ADDRSTART   (DEF_DF_PARAM_STARTADDR+DEF_SELFMONI_DRIFTFAULT_INDEX)
#endif



extern uint32_t DF_StartAddress;
extern unsigned char DF_Rst;
extern unsigned char DF_UpdateInit_Flag;
extern unsigned char DF_UpdateReal_Flag;


#if 0
extern uint8_t DF_Data[256];
extern uint8_t DF_DefaultData[256];
// extern const uint8_t DF_DefaultData[256];
#endif

#if 1
extern __align(4)  uint8_t DF_Data[256];
extern __align(4)  uint8_t DF_DefaultData[256];
// extern const uint8_t DF_DefaultData[256];
#endif




unsigned char Usr_DF_InitSetup(void);


void Usr_DFData_To_Variable(void);

void Usr_DFData_To_DataFlash(void);



#endif







